# This is a secret defining the target cluster for Argo CD capabiliy.
# Once deployed, ArgoDC will pick it up and the cluster will be available for a target for deployments.
apiVersion: v1
kind: Secret
metadata:
  name: local-cluster
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: cluster
stringData:
  name: local-cluster
  server: arn:aws:eks:us-east-1:726728011995:cluster/lowk8
  project: default
