apiVersion: v2
name: cf-cluster-autoscaler
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cluster-autoscaler
    version: 9.46.6
    repository: https://kubernetes.github.io/autoscaler
    condition: cf-cluster-autoscaler.enabled
