# Default values for cf-cluster-autoscaler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cluster-autoscaler:
  enabled: true
  autoDiscovery:
    clusterName: lowk8
  tags:
    - k8s.io/cluster-autoscaler/enabled
