apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: lowk8
  region: us-east-1

addons:
- name: aws-ebs-csi-driver
  podIdentityAssociations:
  - serviceAccountName: ebs-csi-controller-sa
    permissionPolicyARNs: ["arn:aws:iam::aws:policy/service-role/AmazonEBSCSIDriverPolicy"]
    namespace: kube-system
