# Default values for cf-keycloak.
# This is a YAML-formatted file.

cf-keycloak:
  enabled: true

keycloak:
  image:
    tag: 26.1.2-debian-12-r0
  proxy: edge
  auth:
    adminPassword: admin
    adminUser: admin
  tls:
    enabled: false
    existingSecret: lowsandbox-tls
    usePem: true
  ingress:
    enabled: true
    tls: false
    hostname: keycloak.lowsandbox.com
    ingressClassName: alb # haproxy
    pathType: Prefix
    annotations:
      #     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      #      nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:726728011995:certificate/1632b387-345a-4518-a09e-362720af415a
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: "443"
  #    extraTls:
  #      - hosts:
  #          - keycloak.lowsandbox.com
  #        secretName: lowsandbox-tls
  adminIngress:
    enabled: true
    hostname: adminkeycloak.lowsandbox.com
    ingressClassName: alb # haproxy
    pathType: Prefix
  #   extraTls:
  #     - hosts:
  #         - adminkeycloak.lowsandbox.com
  # Based on the ingress controller used secret might be optional
  #       secretName: lowsandbox-tls
  extraEnvVars:
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

global:
  storageClass: "ebs-sc"
