# Default values for cf-keycloak.
# This is a YAML-formatted file.

cf-keycloak:
  enabled: true

keycloak:
  proxy: edge
  auth:
    adminPassword: admin
    adminUser: admin
  tls:
    enabled: false
    existingSecret: lowsandbox-tls
    usePem: true
  ingress:
    enabled: true
    tls: true
    hostname: keycloak.lowsandbox.com
    ingressClassName: nginx
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-tls-verify-client: "off"
    extraTls:
      - hosts:
          - keycloak.lowsandbox.com
        secretName: lowsandbox-tls
  # adminIngress:
  #   enabled: true
  #   hostname: adminkeycloak.lowsandbox.com
  #   ingressClassName: nginx
  #   pathType: Prefix
  #   extraTls:
  #     - hosts:
  #         - adminkeycloak.lowsandbox.com
  #           # Based on the ingress controller used secret might be optional
  #       secretName: lowsandbox-tls
  extraEnvVars:
    - name: PROXY_ADDRESS_FORWARDING
      value: "true"

global:
  storageClass: "ebs-sc"
