apiVersion: v2
name: cf-grafana
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: loki-stack
    version: 2.10.2
    repository: https://grafana.github.io/helm-charts
    condition: loki-stack.enabled
  - name: grafana
    version: 8.4.3
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
 
