apiVersion: v2
name: cf-alloy
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: alloy
    version: 1.0.1
    repository: https://grafana.github.io/helm-charts
    condition: cf-alloy.enabled
